baseurl: "/Handbuch-Jugend-Hackathons"

collections:
    chapters_de:
        output: true
        permalink: /chapters_de/:path/
        language: de
    chapters_nl:
        output: true
        permalink: /chapters_nl/:path/
        language: nl

defaults:
  - scope:
        type: chapters_de
    values:
        layout: chapter
  - scope:
        type: chapters_nl
    values:
        layout: chapter
